// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include <stdio.h>
#include "DisplayButtons.h"

DisplayButtons::DisplayButtons() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void DisplayButtons::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void DisplayButtons::Execute() 
{
   char xString[100];   
   
   for (int axis = 0; axis <= 8; axis++)
   {     
      sprintf(xString, "X Box Controller - Raw Axis %d", axis);
      SmartDashboard::PutNumber(xString, Robot::oi->getXboxJoystick()->GetRawAxis(axis));
   }
   
   for (int button = 0; button < 16; button++)
   {     
      sprintf(xString, "X Box Controller - Button %d", button);
      SmartDashboard::PutBoolean(xString, Robot::oi->getXboxJoystick()->GetRawButton(button));
   }
}

// Make this return true when this Command no longer needs to run execute()
bool DisplayButtons::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void DisplayButtons::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DisplayButtons::Interrupted() {

}
