// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#define P_DEFAULT                   5.0
#define I_DEFAULT                   0.0
#define D_DEFAULT                   0.0

#include "UpdateTurnPIDValues.h"

UpdateTurnPIDValues::UpdateTurnPIDValues() 
{
   SmartDashboard::PutNumber("Turn PID P", P_DEFAULT);
   SmartDashboard::PutNumber("Turn PID I", I_DEFAULT);
   SmartDashboard::PutNumber("Turn PID D", D_DEFAULT);
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void UpdateTurnPIDValues::Initialize()
{
   printf("P %f\n", SmartDashboard::GetNumber("Turn PID P"));
   ((Turnright*)(Robot::oi->turnRight))->SetPID(SmartDashboard::GetNumber("Turn PID P"),
         SmartDashboard::GetNumber("Turn PID I"),
         SmartDashboard::GetNumber("Turn PID D"));
}

// Called repeatedly when this Command is scheduled to run
void UpdateTurnPIDValues::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool UpdateTurnPIDValues::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void UpdateTurnPIDValues::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UpdateTurnPIDValues::Interrupted() {

}
